[[CyrusSASL]]
arch = "aarch64"
git-tree-sha1 = "3ecffdc292707a2ddf0dd11ca25845da517adcbe"
os = "macos"

    [[CyrusSASL.download]]
    sha256 = "44a6234dbb7a13d6be38502bedef98f52d72d65aa867c8cfb2d964f378c9fae5"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.aarch64-apple-darwin.tar.gz"
[[CyrusSASL]]
arch = "aarch64"
git-tree-sha1 = "7e3138bb2c72a3f6f71e6c862babdb8e3c070168"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "1a4942d1eb91e491c3c7eb07e712766558468a785481fb910180e2aaf566b8fd"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.aarch64-linux-gnu.tar.gz"
[[CyrusSASL]]
arch = "aarch64"
git-tree-sha1 = "5fa1781c9a5914507b933ea7ddce7befc6927f7c"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "52aaf962f7b5c318a1c6469fced35f05950ee59f66bfbc5806e718b370143969"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.aarch64-linux-musl.tar.gz"
[[CyrusSASL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fd5c4ae6a0db154c2a43c52563cf80933a80c7e7"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "fa58b7a34b1f9c392cc2a9592f0ca2ef4e46f8a5957411419ea3c3f8ca5fd968"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.armv6l-linux-gnueabihf.tar.gz"
[[CyrusSASL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "155e49ba99600a594ef88eeb006f0783792d7a89"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "6e10209124001d4b68b580a550c0438338934f62c933c610d8d2bebbab311968"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.armv6l-linux-musleabihf.tar.gz"
[[CyrusSASL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c68e8374aec0c15e4aee881eb7e9e4e982d72579"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "af4fe25e78b8f27113ac49c1a343d8ba9240fc455ff71e8f9119b8535aa8f9f5"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.armv7l-linux-gnueabihf.tar.gz"
[[CyrusSASL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e2ca2b46f46f378831dfd1daded7d52a75842d2"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "47e706b8b4c9d99e0abe537cd9b2102a2241b4ac24dc09fe54e8e87cbb018476"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.armv7l-linux-musleabihf.tar.gz"
[[CyrusSASL]]
arch = "i686"
git-tree-sha1 = "b4eac31add3d38bcb17f984c4a6fd7582b1bbad6"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "ef5891cb6399f276354ea68ebceacd81f252430ea3c9e69ae1bd5019d74855b1"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.i686-linux-gnu.tar.gz"
[[CyrusSASL]]
arch = "i686"
git-tree-sha1 = "2ae34799d1abc4f490238cc781ed46b10e28376b"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "c225638f5d9504bff0ad582bbd7d051f80cf8e4bd65948a11cc425ea70bd4022"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.i686-linux-musl.tar.gz"
[[CyrusSASL]]
arch = "i686"
git-tree-sha1 = "72171ca1fd46ff65444353cc5415e249de113dc5"
os = "windows"

    [[CyrusSASL.download]]
    sha256 = "1539ae380dc9d67c19937b3954fffadaf2af0a8b276b93ab8d7249b5e781c129"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.i686-w64-mingw32.tar.gz"
[[CyrusSASL]]
arch = "powerpc64le"
git-tree-sha1 = "472cb1ef702287318c66def0d42d0e020aa172c8"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "f94a65e14b426d3f55905bccb3ef21c9c6918bdf5354f64beb275317433f2a7f"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.powerpc64le-linux-gnu.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "b72dcfd2b35353fbf81f77093201702f9c5f2430"
os = "macos"

    [[CyrusSASL.download]]
    sha256 = "4d94ab037af7bc0adb1f16ea53fb33dd0390f0ec94c6553d1bb9fe26641b9097"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.x86_64-apple-darwin.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "6f64b467d736e277c798c473a06688fbecff5518"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "8aa4cec10e47d8fbfed71ff4249af6e3503b2e1d275b6e2804750340f28f4359"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.x86_64-linux-gnu.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "e82de4abe5d276f5e1ab5ff7b0d4f35bc278bf7a"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "7efe27f0eff18d5d41b0bc75aaa68f8e6c30a1ff8a5a24106d87527db5e7f21b"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.x86_64-linux-musl.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "93c8a7e2abbeca909cb82271c621c7c1eb2ec150"
os = "freebsd"

    [[CyrusSASL.download]]
    sha256 = "e8ec5e5b22cd91392782a5cfd219b7f7da86c2499c14543cecbd604189b39630"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.x86_64-unknown-freebsd.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "608511d2efb2ac88df6f9d581555927dd567eebf"
os = "windows"

    [[CyrusSASL.download]]
    sha256 = "8e6db4b925ef94a92cd91c23a197aca237534faba5db427c4640741f9a91d755"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.29+0/CyrusSASL.v2.1.29.x86_64-w64-mingw32.tar.gz"
