[[CyrusSASL]]
arch = "aarch64"
git-tree-sha1 = "331c573fcd1df3de445a3be7d0da2fa482fc358f"
os = "macos"

    [[CyrusSASL.download]]
    sha256 = "8d9bd0be8fd58b3fda2ed8147ffa7e2e9379e747a472d609435fe958f90f4d37"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.aarch64-apple-darwin.tar.gz"
[[CyrusSASL]]
arch = "aarch64"
git-tree-sha1 = "1c2ab0dfd4fd6adf5c27ad431cc8179510c6941a"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "771cd2291e6cdbcc4e7ca0ed92e2e7119162148be04ad91ab4cadfefc1ea2a9f"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.aarch64-linux-gnu.tar.gz"
[[CyrusSASL]]
arch = "aarch64"
git-tree-sha1 = "08cacacd4dcd715ebb4be230ecc7aa174167b843"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "69a5a6776546fcf6f48022d10b73dbdd5ea1bd2e7488950b0b8cf2f91d0508f3"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.aarch64-linux-musl.tar.gz"
[[CyrusSASL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6bf37aeb2de8aa648dbfa3f1d14872ee28861338"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "552b4684e2a7db01c3657800b8e89c9a228c26848b285bc549cdc79d59cc22b5"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.armv6l-linux-gnueabihf.tar.gz"
[[CyrusSASL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fdf905929e7f458e986afdba640c4a7cebf3f87d"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "902b5160d5ca2ce05b06a7a48bd8dbca8e1ba4adf03e7a1d169ed7000596aa8e"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.armv6l-linux-musleabihf.tar.gz"
[[CyrusSASL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "607ccbb85afbc602dbddc0b1aff57d279c74d814"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "480d19c4f16f71b98eed5e0390e9ea63d79c28616c0559c553e6a92d922f5088"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.armv7l-linux-gnueabihf.tar.gz"
[[CyrusSASL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "118f0bfbdcd8edd67769f8b6ff242c80086c1965"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "8b167b48eba2f368bb7ef505d048b186327a6fc4eefbf90c02b109a71760059d"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.armv7l-linux-musleabihf.tar.gz"
[[CyrusSASL]]
arch = "i686"
git-tree-sha1 = "acb5f2329da9661a6c39a7f5d9193bfc4eb21231"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "dc02bf0ba626198b35dd6380798a8e709c1af45ee57d2e53e765dd2c85bae194"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.i686-linux-gnu.tar.gz"
[[CyrusSASL]]
arch = "i686"
git-tree-sha1 = "4f0451b2e5a6a29b53da17cebe9264f8655edfd2"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "373105acb1900726c9de45b8ebe75132bad8e27b103b491b2e4722a7c1e27fa7"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.i686-linux-musl.tar.gz"
[[CyrusSASL]]
arch = "i686"
git-tree-sha1 = "58bc383307aafeabf62b8b9457373a42ef1a0f9c"
os = "windows"

    [[CyrusSASL.download]]
    sha256 = "7049ccf5b313ca85908600defd341256838cd207cb684b2ab442b6ef2e70aefa"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.i686-w64-mingw32.tar.gz"
[[CyrusSASL]]
arch = "powerpc64le"
git-tree-sha1 = "5984cf5bdb50bb50815361e35d2c29e791d5598d"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "069540188f3f748664e6a131998608f3b8f8d3b4a043fc0239a3a5e263f26cf3"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.powerpc64le-linux-gnu.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "0407d6ea043a9fb3cabb408f38d1284c09d512d0"
os = "macos"

    [[CyrusSASL.download]]
    sha256 = "028f26ae7d4fac4316de815fcca109ccc790b0b177a165fbbd77448b0df68d54"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.x86_64-apple-darwin.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "e34cc22fd10f2c214f2dcb7316143ff583f85773"
libc = "glibc"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "eca55ccb52a6be4dca37c631f0ca075df38326715014c8bdb885906b6aaa5285"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.x86_64-linux-gnu.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "afbe225af97c9487ecf3bf775999f9f446446d82"
libc = "musl"
os = "linux"

    [[CyrusSASL.download]]
    sha256 = "aea7d73f793fa36abbc8c96fa72435e3730e2d3d7c4a695701f6173ab634e2ad"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.x86_64-linux-musl.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "11965350a16e7d80b19418ad1da57f71148916c0"
os = "freebsd"

    [[CyrusSASL.download]]
    sha256 = "d6ce24816f2768abc7a8012e9a237db84c3637bd7a9bd12235717e139abed24f"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.x86_64-unknown-freebsd.tar.gz"
[[CyrusSASL]]
arch = "x86_64"
git-tree-sha1 = "d3dd0500774e6fef7462170cbd8fe8017ddd2598"
os = "windows"

    [[CyrusSASL.download]]
    sha256 = "009fb57a90429499c60bc8f49391a0d1fd222b366e564c24e51e8f113adfaebb"
    url = "https://github.com/JuliaBinaryWrappers/CyrusSASL_jll.jl/releases/download/CyrusSASL-v2.1.28+0/CyrusSASL.v2.1.28.x86_64-w64-mingw32.tar.gz"
